# Generated by Django 2.0.6 on 2018-07-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('website', models.URLField(null=True)),
                ('user_level', models.CharField(choices=[(1, 'level_1'), (2, 'level_2')], default=1, max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('kr', 'Korean'), ('cn', 'Chinese')], default='en', max_length=2)),
                ('deleted_date', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
