# Generated by Django 2.0.6 on 2018-06-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20180622_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('kr', 'Korean'), ('cn', 'Chinese')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='user_level',
            field=models.CharField(choices=[(1, 'level_1'), (2, 'level_2')], default=1, max_length=10),
        ),
    ]
