# Generated by Django 2.0.6 on 2018-08-12 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tosca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplatefile',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicetemplatefile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=2, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicetemplatefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
