# Generated by Django 2.0.6 on 2018-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='build_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='fixed_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='major_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='minor_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='version',
            name='qualifier',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
