# Generated by Django 2.0.6 on 2018-08-12 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tosca', '0002_auto_20180812_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetemplatefile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
