# Generated by Django 2.0.6 on 2018-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosca', '0003_auto_20180812_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplatefile',
            name='template_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
