# Generated by Django 2.0.6 on 2018-08-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosca', '0004_servicetemplatefile_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetemplatefile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='servicetemplatefile',
            name='user',
        ),
    ]
