# Generated by Django 2.0.6 on 2018-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosca', '0006_auto_20180812_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplatefile',
            name='template_id',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
