# Generated by Django 2.0.6 on 2018-08-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tosca', '0007_servicetemplatefile_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('state', models.IntegerField(default=0)),
                ('template_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tosca.ServiceTemplateFile')),
            ],
        ),
    ]
